#lang racket/base

(provide 
  *bidi-classes*
  *case-folding-status*
  *combining-classes*
  *decomposition-compatibility-tags*
  *general-categories*
  *line-breaks*
  *name-alias-types*
  *numeric-types*)

(define *bidi-classes*
  '((L . "Left-to-right")
    (R . "Right-to-left")
    (EN . "European Number")
    (ES . "European Separator")
    (ET . "European Terminator")
    (AN . "Arabic Number")
    (CS . "Common Separator")
    (B . "Paragraph Separator")
    (S . "Segment Separator")
    (WS . "White Space")
    (ON . "Other Neutral")
    (BN . "Boundary Neutral")
    (NSM . "Non-spacing Mark")
    (AL . "Arabic Letter")
    (LRO . "Left-to-right Override")
    (RLO . "Right-to-left Override")
    (LRE . "Left-to-right Embedding")
    (PDF . "Pop Directional Formatting")
    (LRI . "Left-to-right Isolate")
    (RLI . "Right-to-left Isolate")
    (FSI . "First Strong Isolate")
    (PDI . "Pop Directional Isolate")))

(define *case-folding-status*
  '((common . "common case folding, common mappings shared by both simple and full mappings")
    (simple . "simple case folding, mappings to single characters where different from full")
    (full . "full case folding, mappings that cause strings to grow in length. Multiple characters are separated by spaces")
    (turkic . "special case for uppercase I and dotted uppercase I")))

(define *codepoint-types*
  '((graphic . "Letter, mark, number, punctuation, symbol, and spaces")
    (format . "Invisible but affects neighboring characters; includes line/paragraph separators")
    (control . "Usage defined by protocols or standards outside the Unicode Standard")
    (private-use . "Usage defined by private agreement outside the Unicode Standard")
    (surrogate . "Permanently reserved for UTF-16; restricted interchange")
    (non-character . "Permanently reserved for internal usage; restricted interchange")
    (reserved . "Reserved for future assignment; restricted interchange")))

(define *combining-classes*
  '(
    (0 . "Spacing and enclosing marks; also many vowel and consonant signs, even if nonspacing")
    (1 . "Marks which overlay a base letter or symbol")
    (6 . "Diacritic reading marks for CJK unified ideographs")
    (7 . "Diacritic nukta marks in Brahmi-derived scripts")
    (8 . "Hiragana/Katakana voicing marks")
    (9 . "Viramas")
    (10 . "Start of fixed position classes")
    (199 . "End of fixed position classes")
    (200 . "Marks attached at the bottom left")
    (202 . "Marks attached directly below")
    (204 . "Marks attached at the bottom right")
    (208 . "Marks attached to the left")
    (210 . "Marks attached to the right")
    (212 . "Marks attached at the top left")
    (214 . "Marks attached directly above")
    (216 . "Marks attached at the top right")
    (218 . "Distinct marks at the bottom left")
    (220 . "Distinct marks directly below")
    (222 . "Distinct marks at the bottom right")
    (224 . "Distinct marks to the left")
    (226 . "Distinct marks to the right")
    (228 . "Distinct marks at the top left")
    (230 . "Distinct marks directly above")
    (232 . "Distinct marks at the top right")
    (233 . "Distinct marks subtending two bases")
    (234 . "Distinct marks extending above two bases")
    (240 . "Greek iota subscript only")))
    
(define *decomposition-compatibility-tags*
  '((font> "Font variant (for example, a blackletter form)")
    (noBreak . "No-break version of a space or hyphen")
    (initial. "Initial presentation form (Arabic)")
    (medial . "Medial presentation form (Arabic)")
    (final . "Final presentation form (Arabic)")
    (isolated . "Isolated presentation form (Arabic)")
    (circle . "Encircled form")
    (super . "Superscript form")
    (sub . "Subscript form")
    (vertical . "Vertical layout presentation form")
    (wide . "Wide (or zenkaku) compatibility character")
    (narrow . "Narrow (or hankaku) compatibility character")
    (small . "Small variant form (CNS compatibility)")
    (square . "CJK squared font variant")
    (fraction . "Vulgar fraction form")
    (compat . "Otherwise unspecified compatibility character")))

(define *general-categories*
  '((Cc . "Control")
    (Cf . "Format")
    (Cn . "Unassigned")
    (Co . "Private use")
    (Cs . "Surrogate")
    (Ll . "Lowercase letter")
    (Lm . "Modifier letter")
    (Lo . "Other letter")
    (Lt . "Titlecase letter")
    (Lu . "Uppercase letter")
    (Mc . "Combining spacing mark")
    (Me . "Enclosing mark")
    (Mn . "Non-spacing mark")
    (Nd . "Decimal digit number")
    (Nl . "Letter number")
    (No . "Other number")
    (Pc . "Connector punctuation")
    (Pd . "Dash punctuation")
    (Pe . "Close punctuation")
    (Pi . "Initial quote punctuation")
    (Pf . "Final quote punctuation")
    (Po . "Other punctuation")
    (Ps . "Open punctuation")
    (Sc . "Currency symbol")
    (Sk . "Modifier symbol")
    (Sm . "Math symbol")
    (So . "Other symbol")
    (Zl . "Line separator")
    (Zp . "Paragraph separator")
    (Zs . "Space separator")))

(define *line-breaks* 
  '(
    ;; Non-tailorable Line Breaking Classes
    (BK . "Mandatory Break")
    (CR . "Carriage Return")
    (LF . "Line Feed")
    (CM . "Combining Mark")
    (NL . "Next Line")
    (SG . "Surrogate")
    (WJ . "Word Joiner")
    (ZW . "Zero Width Space")
    (GL . "Non-breaking ('Glue')")
    (SP . "Space")
    (ZWJ . "Zero Width Joiner")
    ;; Break Opportunities
    (B2 . "Break Opportunity Before and After")
    (BA . "Break After")
    (BB . "Break Before")
    (HY . "Hyphen")
    (CB . "Contingent Break Opportunity")
    ;; Characters Prohibiting Certain Breaks
    (CL . "Close Punctuation")
    (CP . "Close Parenthesis")
    (EX . "Exclamation/Interrogation")
    (IN . "Inseparable")
    (NS . "Nonstarter")
    (OP . "Open Punctuation")
    (QU . "Quotation")
    ;;Numeric Context
    (IS . "Infix Numeric Separator")
    (NU . "Numeric")
    (PO . "Postfix Numeric")
    (PR . "Prefix Numeric")
    (SY . "Symbols Allowing Break After")
    ;; Other Characters
    (AI . "Ambiguous (Alphabetic or Ideographic)")
    (AL . "Alphabetic")
    (CJ . "Conditional Japanese Starter")
    (EB . "Emoji Base")
    (EM . "Emoji Modifier")
    (H2 . "Hangul LV Syllable")
    (H3 . "Hangul LVT Syllable")
    (HL . "Hebrew Letter")
    (ID . "Ideographic")
    (JL . "Hangul L Jamo")
    (JV . "Hangul V Jamo")
    (JT . "Hangul T Jamo")
    (RI . "Regional Indicator")
    (SA . "Complex Context Dependent (South East Asian)")
    (XX . "Unknown")
  ))

(define *name-alias-types*
  '((abbreviation . "Commonly occurring abbreviations (or acronyms) for control codes, format characters, spaces, and variation selectors") 
    (alternate . "A few widely used alternate names for format characters") 
    (control . "ISO 6429 names for C0 and C1 control functions, and other commonly occurring names for control codes") 
    (correction . "Corrections for serious problems in the character names") 
    (figment . "Several documented labels for C1 control code points which were never actually approved in any standard")))

(define *numeric-types*
  '((decimal . "The value of the character is represented with an integer value (limited to the range 0..9)")
    (digit . "As decimal, but also covers digits that need special handling, such as the compatibility superscript digits")
    (numeric . "The value of the character is represented with a positive or negative integer or rational number")))